***Project 3 EEP 153***

**Authors:** Daniel Canales, Amanda Edwards, Christian Gee, Ziton Xu, Chloe Shih

In [23]:
!pip install -r requirements.txt

Requirement already satisfied: CFEDemands in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (0.8.2)
Requirement already satisfied: ConsumerDemands in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (0.5.0)
Requirement already satisfied: ligonlibrary in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (0.2.0)
Requirement already satisfied: plotly in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (6.6.0)
Requirement already satisfied: ipympl in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (0.9.8)
Requirement already satisfied: fsspec in /srv/conda/lib/python3.11/site-packages (from CFEDemands->-r requirements.txt (line 1)) (2026.3.0)
Requirement already satisfied: importlib-metadata>=6.7.0 in /srv/conda/lib/python3.11/site-packages (from CFEDemands->-r requirements.txt (line 1)) (8.7.0)
Requirement already satisfied: matplotlib>=3.5.1 in /srv/conda/lib/python3.11/site-packages (from CFEDemands->-r requirements.txt (line 1)) (3.10.8)
Requirement already satisfied: numpy>=1.21.5 in /srv/conda/lib/python3.11/site-packages (from CFEDemands->-r requirements.txt (line 1)) (2.2.6)
Requirement already satisfied: pandas>=1.3.5 in /srv/conda/lib/python3.11/site-packages (from CFEDemands->-r requirements.txt (line 1)) (3.0.2)
Requirement already satisfied: scikit-learn in /srv/conda/lib/python3.11/site-packages (from CFEDemands->-r requirements.txt (line 1)) (1.6.0)
Requirement already satisfied: scipy>=1.7.3 in /srv/conda/lib/python3.11/site-packages (from CFEDemands->-r requirements.txt (line 1)) (1.14.1)
Requirement already satisfied: google-api-python-client>=2.178.0 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary->-r requirements.txt (line 3)) (2.190.0)
Requirement already satisfied: google-auth-oauthlib>=1.2.2 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary->-r requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: gspread>=5.12.0 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary->-r requirements.txt (line 3)) (5.12.4)
Requirement already satisfied: gspread-pandas>=3.3.0 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary->-r requirements.txt (line 3)) (3.3.0)
Requirement already satisfied: openpyxl>=3.1.5 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary->-r requirements.txt (line 3)) (3.1.5)
Requirement already satisfied: python-gnupg>=0.5.2 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary->-r requirements.txt (line 3)) (0.5.6)
Requirement already satisfied: python-magic>=0.4.27 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary->-r requirements.txt (line 3)) (0.4.27)
Requirement already satisfied: thefuzz>=0.22.1 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary->-r requirements.txt (line 3)) (0.22.1)
Requirement already satisfied: narwhals>=1.15.1 in /srv/conda/lib/python3.11/site-packages (from plotly->-r requirements.txt (line 4)) (2.17.0)
Requirement already satisfied: packaging in /srv/conda/lib/python3.11/site-packages (from plotly->-r requirements.txt (line 4)) (24.2)
Requirement already satisfied: ipython<10 in /srv/conda/lib/python3.11/site-packages (from ipympl->-r requirements.txt (line 5)) (9.10.0)
Requirement already satisfied: ipywidgets<9,>=7.6.0 in /srv/conda/lib/python3.11/site-packages (from ipympl->-r requirements.txt (line 5)) (8.1.5)
Requirement already satisfied: pillow in /srv/conda/lib/python3.11/site-packages (from ipympl->-r requirements.txt (line 5)) (11.1.0)
Requirement already satisfied: traitlets<6 in /srv/conda/lib/python3.11/site-packages (from ipympl->-r requirements.txt (line 5)) (5.14.3)
Requirement already satisfied: decorator>=4.3.2 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 5)) (5.1.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 5)) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 5)) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 5)) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 5)) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 5)) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 5)) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 5)) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 5)) (4.12.2)
Requirement already satisfied: comm>=0.1.3 in /srv/conda/lib/python3.11/site-packages (from ipywidgets<9,>=7.6.0->ipympl->-r requirements.txt (line 5)) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.12 in /srv/conda/lib/python3.11/site-packages (from ipywidgets<9,>=7.6.0->ipympl->-r requirements.txt (line 5)) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.12 in /srv/conda/lib/python3.11/site-packages (from ipywidgets<9,>=7.6.0->ipympl->-r requirements.txt (line 5)) (3.0.16)
Requirement already satisfied: contourpy>=1.0.1 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.5.1->CFEDemands->-r requirements.txt (line 1)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.5.1->CFEDemands->-r requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.5.1->CFEDemands->-r requirements.txt (line 1)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.5.1->CFEDemands->-r requirements.txt (line 1)) (1.4.9)
Requirement already satisfied: pyparsing>=3 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.5.1->CFEDemands->-r requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.5.1->CFEDemands->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: wcwidth in /srv/conda/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython<10->ipympl->-r requirements.txt (line 5)) (0.6.0)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /srv/conda/lib/python3.11/site-packages (from google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (0.22.0)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in /srv/conda/lib/python3.11/site-packages (from google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (2.41.1)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /srv/conda/lib/python3.11/site-packages (from google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (0.3.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /srv/conda/lib/python3.11/site-packages (from google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (2.30.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /srv/conda/lib/python3.11/site-packages (from google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (4.2.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /srv/conda/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /srv/conda/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (6.33.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /srv/conda/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (1.27.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /srv/conda/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (2.32.3)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in /srv/conda/lib/python3.11/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (6.2.6)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /srv/conda/lib/python3.11/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /srv/conda/lib/python3.11/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (4.9.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /srv/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /srv/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /srv/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /srv/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (2026.2.25)
Requirement already satisfied: pyasn1>=0.1.3 in /srv/conda/lib/python3.11/site-packages (from rsa<5,>=3.1.4->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client>=2.178.0->ligonlibrary->-r requirements.txt (line 3)) (0.6.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /srv/conda/lib/python3.11/site-packages (from google-auth-oauthlib>=1.2.2->ligonlibrary->-r requirements.txt (line 3)) (2.0.0)
Requirement already satisfied: zipp>=3.20 in /srv/conda/lib/python3.11/site-packages (from importlib-metadata>=6.7.0->CFEDemands->-r requirements.txt (line 1)) (3.23.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /srv/conda/lib/python3.11/site-packages (from jedi>=0.18.1->ipython<10->ipympl->-r requirements.txt (line 5)) (0.8.6)
Requirement already satisfied: et_xmlfile in /srv/conda/lib/python3.11/site-packages (from openpyxl>=3.1.5->ligonlibrary->-r requirements.txt (line 3)) (2.0.0)
Requirement already satisfied: ptyprocess>=0.5 in /srv/conda/lib/python3.11/site-packages (from pexpect>4.3->ipython<10->ipympl->-r requirements.txt (line 5)) (0.7.0)
Requirement already satisfied: six>=1.5 in /srv/conda/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=3.5.1->CFEDemands->-r requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: oauthlib>=3.0.0 in /srv/conda/lib/python3.11/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=1.2.2->ligonlibrary->-r requirements.txt (line 3)) (3.3.1)
Requirement already satisfied: executing>=1.2.0 in /srv/conda/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython<10->ipympl->-r requirements.txt (line 5)) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /srv/conda/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython<10->ipympl->-r requirements.txt (line 5)) (3.0.1)
Requirement already satisfied: pure_eval in /srv/conda/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython<10->ipympl->-r requirements.txt (line 5)) (0.2.3)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.0.0 in /srv/conda/lib/python3.11/site-packages (from thefuzz>=0.22.1->ligonlibrary->-r requirements.txt (line 3)) (3.14.3)
Requirement already satisfied: joblib>=1.2.0 in /srv/conda/lib/python3.11/site-packages (from scikit-learn->CFEDemands->-r requirements.txt (line 1)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /srv/conda/lib/python3.11/site-packages (from scikit-learn->CFEDemands->-r requirements.txt (line 1)) (3.6.0)

In [24]:
Panama_data = 'https://docs.google.com/spreadsheets/d/1tYmqzz4VqM5rd4aeO6zB4wL9ADcoTdvTPKZF5zgX7a4/edit?gid=1443689638#gid=1443689638'

In [25]:
import pandas as pd 
import numpy as np
from ligonlibrary.sheets import read_sheets

### Sheets to DataFrames (Panama)

In [26]:
x = read_sheets(Panama_data, sheet='Food Expenditures (2008)')
p = read_sheets(Panama_data, sheet='Food Prices (2008)')
d = read_sheets(Panama_data, sheet='Household Characteristics')

In [27]:
x.head()
p.head()
d.head()

,i,t,m,men,women,girls,boys,Males 00-03,Females 00-03,Males 04-08,...,Females 09-13,Males 14-18,Females 14-18,Males 19-30,Females 19-30,Males 31-50,Females 31-50,Males 51-99,Females 51-99,log HSize
0,1997125,1997,Herrera,1,1,0,1,0,0,0,...,0,0,0,0,0,0,1,1,0,1.098612
1,1997160,1997,Herrera,1,2,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1.098612
2,1997170,1997,Bocas Del Toro,1,1,4,3,1,2,1,...,1,1,1,0,0,0,1,1,0,2.197225
3,1997177,1997,Bocas Del Toro,1,4,5,9,2,1,4,...,3,2,0,0,2,0,2,1,0,2.944439
4,1997178,1997,Bocas Del Toro,2,2,2,1,0,0,0,...,0,0,1,2,0,0,1,0,1,1.945910

In [28]:
x.head()
x.columns

Index(['i', 't', 'm', 'j', 'Expenditure'], dtype='str')

In [29]:
x.head()

       i     t               m             j  Expenditure
0  20081  2008  Bocas Del Toro     Ahí Verde         0.75
1  20081  2008  Bocas Del Toro         Arroz         7.35
2  20081  2008  Bocas Del Toro       Arvejas         0.75
3  20081  2008  Bocas Del Toro        Azúcar         1.60
4  20081  2008  Bocas Del Toro  Carne De Res        18.00

In [30]:
# Convert expenditure data from long to wide
x = x.pivot_table(
    index='i',
    columns='j',
    values='Expenditure',
    aggfunc='sum'
)

x.head()

j,Aceite Vegetal,Aguacates,Ahí Verde,Ajo,Alimento Infantil,Apio,Arroz,Arvejas,Azúcar,Café Y Té,...,Sardina Y Atún,"Sodas, Refrescos Y Jugos",Sopa Enlatada,Tomate,Viscera De Res,Visceras De Pollo O Gallina,Yuca,Zanahoria,Zapallo / Chayote,Ñame
i,,,,,,,,,,,,,,,,,,,,,
20081,NaN,NaN,0.75,NaN,NaN,NaN,7.35,0.75,1.60,NaN,...,0.55,3.0,0.9,1.6,NaN,NaN,0.7,0.80,0.5,NaN
20082,4.25,NaN,2.00,NaN,NaN,NaN,12.25,0.95,NaN,NaN,...,2.00,NaN,0.4,2.0,NaN,NaN,NaN,NaN,NaN,1.0
20083,4.50,3.00,0.80,NaN,NaN,NaN,2.45,NaN,1.75,NaN,...,NaN,5.0,1.8,2.5,NaN,NaN,NaN,NaN,NaN,NaN
20084,4.25,1.50,0.75,NaN,NaN,NaN,10.50,NaN,3.50,2.35,...,NaN,4.0,NaN,NaN,NaN,NaN,0.7,0.75,NaN,NaN
20085,4.25,2.25,1.50,NaN,NaN,1.5,4.90,NaN,NaN,NaN,...,NaN,35.0,1.8,NaN,NaN,NaN,NaN,NaN,0.5,1.6

In [31]:
d = d.set_index('i')
d.head()

,t,m,men,women,girls,boys,Males 00-03,Females 00-03,Males 04-08,Females 04-08,...,Females 09-13,Males 14-18,Females 14-18,Males 19-30,Females 19-30,Males 31-50,Females 31-50,Males 51-99,Females 51-99,log HSize
i,,,,,,,,,,,,,,,,,,,,,
1997125,1997,Herrera,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,1,1,0,1.098612
1997160,1997,Herrera,1,2,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1.098612
1997170,1997,Bocas Del Toro,1,1,4,3,1,2,1,0,...,1,1,1,0,0,0,1,1,0,2.197225
1997177,1997,Bocas Del Toro,1,4,5,9,2,1,4,1,...,3,2,0,0,2,0,2,1,0,2.944439
1997178,1997,Bocas Del Toro,2,2,2,1,0,0,0,1,...,0,0,1,2,0,0,1,0,1,1.945910

In [32]:
x = x.replace(0, np.nan)
y = np.log(x)
y.head()

j,Aceite Vegetal,Aguacates,Ahí Verde,Ajo,Alimento Infantil,Apio,Arroz,Arvejas,Azúcar,Café Y Té,...,Sardina Y Atún,"Sodas, Refrescos Y Jugos",Sopa Enlatada,Tomate,Viscera De Res,Visceras De Pollo O Gallina,Yuca,Zanahoria,Zapallo / Chayote,Ñame
i,,,,,,,,,,,,,,,,,,,,,
20081,NaN,NaN,-0.287682,NaN,NaN,NaN,1.994700,-0.287682,0.470004,NaN,...,-0.597837,1.098612,-0.105361,0.470004,NaN,NaN,-0.356675,-0.223144,-0.693147,NaN
20082,1.446919,NaN,0.693147,NaN,NaN,NaN,2.505526,-0.051293,NaN,NaN,...,0.693147,NaN,-0.916291,0.693147,NaN,NaN,NaN,NaN,NaN,0.000000
20083,1.504077,1.098612,-0.223144,NaN,NaN,NaN,0.896088,NaN,0.559616,NaN,...,NaN,1.609438,0.587787,0.916291,NaN,NaN,NaN,NaN,NaN,NaN
20084,1.446919,0.405465,-0.287682,NaN,NaN,NaN,2.351375,NaN,1.252763,0.854415,...,NaN,1.386294,NaN,NaN,NaN,NaN,-0.356675,-0.287682,NaN,NaN
20085,1.446919,0.810930,0.405465,NaN,NaN,0.405465,1.589235,NaN,NaN,NaN,...,NaN,3.555348,0.587787,NaN,NaN,NaN,NaN,NaN,-0.693147,0.470004

In [33]:
use = y.index.intersection(d.index)

y = y.loc[use]
d = d.loc[use]

print(y.shape)
print(d.shape)

(6836, 81)
(6836, 21)

### Estimation Panama

In [34]:
from cfe.estimation import drop_columns_wo_covariance
from cfe import Regression

x_raw = read_sheets(Panama_data, sheet='Food Expenditures (2008)')
d_raw = read_sheets(Panama_data, sheet='Household Characteristics')

y = (x_raw.set_index(['i', 't', 'm', 'j'])['Expenditure'].replace(0, np.nan))
y = np.log(y)

d = d_raw.set_index(['i', 't', 'm'])

result = Regression(y=y, d=d)

In [35]:
result.get_beta()

j
Aceite Vegetal                  0.415991
Ajo                             0.288771
Arroz                           0.250081
Azúcar                          0.303668
Café Y Té                       0.307942
Carne De Res                    0.695826
Carnes De Puerco                0.613415
Cebolla                         0.467811
Cereales Y Cremas               0.642493
Cigarrillo Y Tabaco             0.962572
Condimentos                     0.615954
Embutidos                       0.634336
Frijoles                        0.260462
Galletas / Pasteles Y Dulces    0.662308
Harina De Trigo                 0.356053
Huevos De Gallina               0.458651
Lecha Evaporada                 0.545697
Leche En Polvo                  0.289263
Lentejas                        0.368234
Maíz De Grano                   0.292204
Pan De Sal Y Pan De Dulce       0.753623
Pastas Alimenticias             0.550472
Pastas De Tomate                0.503155
Pastillas Y Confites            0.729585
Pescados                        0.529315
Picaritas                       0.939743
Pollo O Gallina                 0.645607
Porotos                         0.345504
Queso (Blanco Y Amarillo)       0.579190
Raspados Y Duros                0.629676
Sal                             0.174216
Sardina Y Atún                  0.574545
Sodas, Refrescos Y Jugos        0.861118
Sopa Enlatada                   0.561324
Name: beta, dtype: float64

### Results for Panama

In [36]:
result.get_gamma()

k,men,women,girls,boys,Males 00-03,Females 00-03,Males 04-08,Females 04-08,Males 09-13,Females 09-13,Males 14-18,Females 14-18,Males 19-30,Females 19-30,Males 31-50,Females 31-50,Males 51-99,Females 51-99,log HSize,Constant
j,,,,,,,,,,,,,,,,,,,,
Aceite Vegetal,0.002533,-0.357269,-0.445817,-0.059863,-0.076538,0.363888,0.006827,0.373265,0.008509,0.395257,0.020255,0.377062,-0.008170,0.339975,-0.011209,0.404283,0.003178,0.339799,0.342120,1.184752
Ajo,0.027699,-0.110525,-0.214889,-0.011194,0.007124,0.225632,-0.024636,0.204637,0.009888,0.190763,0.023106,0.209420,-0.030596,0.084680,0.003987,0.102754,0.027529,0.125501,0.079852,-0.671768
Arroz,-0.272187,-0.614727,-0.552876,-0.292783,0.189522,0.472702,0.233456,0.475730,0.336911,0.569021,0.361623,0.556497,0.329595,0.541919,0.348750,0.514682,0.340383,0.553044,0.594265,1.903947
Azúcar,-0.431205,-0.358655,-0.295694,-0.433964,0.447565,0.358332,0.482738,0.372947,0.522795,0.386311,0.522234,0.347403,0.471047,0.333766,0.487860,0.364839,0.586129,0.425075,0.301190,0.439945
Café Y Té,0.097222,0.088335,0.159033,0.028359,0.018104,-0.114590,-0.040047,-0.133886,0.004860,-0.159876,0.033251,-0.089263,-0.053887,-0.113523,0.036092,-0.003167,0.127310,0.027610,-0.010536,0.658230
Carne De Res,0.595127,-2.285380,-2.504856,0.541709,-0.644467,2.372075,-0.649517,2.418631,-0.608824,2.415609,-0.628551,2.428312,-0.588648,2.271613,-0.530560,2.349904,-0.535828,2.253881,0.416919,1.972076
Carnes De Puerco,-0.546831,0.159425,0.033114,-0.624868,0.526590,-0.109814,0.588701,-0.092415,0.566078,-0.102491,0.630046,-0.082208,0.550530,-0.172967,0.608062,-0.144423,0.623627,-0.206983,0.306282,1.609093
Cebolla,-0.777071,0.076194,0.052334,-0.755154,0.744916,-0.052180,0.745508,-0.093531,0.737989,-0.046190,0.777949,-0.047138,0.788424,-0.084306,0.838118,-0.065677,0.881825,-0.050972,0.171356,-0.100548
Cereales Y Cremas,-0.052397,-0.130820,-0.263697,-0.102352,0.018835,0.198916,0.081181,0.218332,-0.029693,0.087692,-0.029286,0.106766,0.005311,0.090241,-0.040359,0.205524,-0.160620,0.042752,0.426647,0.768024
Cigarrillo Y Tabaco,-0.291389,-0.212756,0.179657,0.116004,-0.301361,-0.035886,-0.403034,-0.506240,-0.280780,-0.343727,-0.062254,-0.202056,0.382341,0.311451,0.273856,0.662813,0.216024,0.080903,0.026934,1.158467
Condimentos,0.007537,0.074741,-0.005613,-0.105618,-0.046925,-0.060430,0.056666,-0.000481,0.062651,-0.023397,-0.007437,-0.089298,-0.005871,-0.073063,-0.048900,-0.069251,-0.108314,-0.120097,0.318970,-0.310909
Embutidos,0.040583,0.031526,-0.039026,-0.082636,-0.071817,-0.096042,0.035567,-0.012120,0.055329,0.005794,0.031193,-0.032459,-0.022350,0.014688,-0.018067,0.108874,-0.051766,0.004053,0.316306,0.931102
Frijoles,0.075073,-0.399238,-0.353165,0.067546,-0.010664,0.415979,-0.027323,0.404402,0.057159,0.439777,0.013924,0.453979,0.016619,0.414244,0.010600,0.368517,0.082312,0.421468,-0.026389,0.049590
Galletas / Pasteles Y Dulces,-0.095398,-0.558068,-0.477993,-0.013826,-0.108397,0.468593,0.036117,0.493722,-0.070220,0.446393,-0.082716,0.453596,0.060768,0.544194,0.041938,0.689411,0.013335,0.605045,0.281981,0.324835
Harina De Trigo,0.042312,-0.037165,-0.135919,0.095306,-0.063414,0.178258,-0.026772,0.228273,0.003615,0.306174,0.104259,0.232538,0.062070,0.068343,0.013522,0.024332,0.044339,0.072790,-0.028046,-0.005962
Huevos De Gallina,0.531585,0.037662,-0.054806,0.596474,-0.637650,-0.009663,-0.620972,0.021209,-0.683691,0.027656,-0.595887,0.038487,-0.574063,-0.051463,-0.559934,0.005948,-0.512510,-0.049163,0.353075,0.503854
Lecha Evaporada,-0.084767,-0.049606,-0.059909,-0.053625,-0.000523,0.024752,-0.080341,-0.019230,-0.069572,-0.050709,0.013510,-0.068788,-0.040395,-0.030149,-0.002767,0.006895,0.041792,0.027906,0.509452,0.621925
Leche En Polvo,-0.146602,-0.168833,-0.339817,0.074495,0.242312,0.641804,-0.139757,0.194953,-0.199922,0.136889,-0.124250,0.107096,0.053485,0.163844,0.063271,0.223610,0.033039,0.126717,0.431093,1.854845
Lentejas,-0.181295,0.162858,0.120202,-0.221842,0.260253,-0.094010,0.273273,-0.075760,0.316638,-0.033641,0.305024,-0.032719,0.290731,-0.174876,0.291301,-0.196926,0.339653,-0.178747,0.010795,0.164385
Maíz De Grano,-0.076343,-0.160696,0.046888,0.026779,0.018550,-0.044660,-0.098906,-0.005516,-0.115446,-0.059316,-0.047388,-0.065668,-0.018393,0.009880,-0.035088,0.042757,0.247158,0.008819,0.496588,0.336473
Pan De Sal Y Pan De Dulce,1.848245,0.040293,-0.060865,1.914148,-2.045401,-0.079191,-1.944283,-0.043434,-1.921620,-0.038337,-1.935514,0.005370,-1.847034,-0.031524,-1.854227,0.111034,-1.846649,0.055826,0.498030,1.029461
Pastas Alimenticias,-0.413523,-0.957877,-1.029478,-0.429987,0.419421,1.004955,0.422908,1.025035,0.431854,1.034319,0.493736,1.068191,0.461008,0.961213,0.454387,0.989552,0.464156,0.971832,0.189538,0.261334
Pastas De Tomate,-0.420829,-0.393631,-0.525295,-0.421911,0.293753,0.455400,0.356456,0.452809,0.365263,0.443295,0.385054,0.437689,0.403526,0.366340,0.401950,0.393878,0.358245,0.350787,0.385745,0.447929
Pastillas Y Confites,-0.072094,-0.111583,0.019194,-0.037411,-0.074091,-0.098333,-0.029441,0.106836,-0.031748,-0.069583,-0.051608,-0.113846,0.069741,-0.110047,0.030988,0.083609,-0.023465,0.108740,0.615402,-0.765347
Pescados,-0.482314,0.154137,-0.083961,-0.664724,0.649241,0.094402,0.639423,0.059390,0.633953,0.058256,0.647073,0.047544,0.545535,-0.129579,0.557617,0.008202,0.570413,-0.067644,0.085625,1.282447
Picaritas,-0.124076,-0.034535,-0.126351,-0.052881,-0.128545,-0.029405,0.013953,0.012448,-0.026752,0.071597,-0.113684,-0.025072,0.137722,-0.131192,-0.017169,-0.034120,-0.042462,-0.025102,0.677400,0.133954
Pollo O Gallina,-0.523334,-0.426528,-0.489485,-0.531799,0.418403,0.400548,0.454562,0.403355,0.471815,0.433391,0.497328,0.462512,0.526963,0.427176,0.549685,0.520621,0.545442,0.481553,0.486222,1.955713
Porotos,-0.092240,0.812853,0.772185,-0.164218,0.218913,-0.707394,0.217166,-0.717022,0.243784,-0.701662,0.230739,-0.688523,0.184219,-0.815974,0.206898,-0.832704,0.228206,-0.799665,-0.004280,0.332518
Queso (Blanco Y Amarillo),0.338357,0.138531,0.050774,0.393442,-0.511273,-0.217550,-0.434810,-0.137062,-0.459029,-0.160346,-0.457858,-0.125389,-0.379442,-0.138573,-0.380226,-0.050392,-0.408257,-0.095361,0.365683,0.979627
Raspados Y Duros,0.079708,-0.049715,0.016644,-0.076997,-0.000011,-0.040093,0.130798,-0.075117,0.118686,-0.093173,0.065391,0.074297,-0.188830,0.054681,-0.108446,0.046991,-0.014919,-0.000739,0.417565,-0.265900
Sal,0.337556,-0.152533,-0.075778,0.300438,-0.281341,0.096477,-0.242134,0.120087,-0.203664,0.134098,-0.194696,0.125919,-0.273816,0.124464,-0.242263,0.092219,-0.196647,0.187981,0.065981,-0.973597
Sardina Y Atún,0.001831,-0.548676,-0.568801,0.057641,-0.079719,0.576824,-0.057352,0.612078,-0.057966,0.612350,-0.012978,0.569678,0.081904,0.560347,0.079058,0.573858,0.106631,0.578590,0.084158,0.684811
"Sodas, Refrescos Y Jugos",2.049300,-1.389778,-1.526660,2.041643,-2.147116,1.477150,-2.092119,1.462508,-2.124120,1.420639,-2.126637,1.411475,-2.076169,1.391370,-2.102698,1.511244,-2.113193,1.350217,0.418937,1.020495
Sopa Enlatada,0.044398,-0.359932,-0.557340,0.010020,-0.002978,0.567275,0.034001,0.580939,0.003147,0.539413,0.032149,0.545223,0.039232,0.377793,-0.036977,0.369375,-0.014129,0.344310,0.017890,0.176592

### Sheets to Data Frame (Serbia)

In [38]:
Serbia_data = 'https://docs.google.com/spreadsheets/d/1GFu5qKhA6kx2Qjadu7Gnr9853FpPcZxpO4QzAbLlWos/edit?gid=353863528#gid=353863528'

In [39]:
x = read_sheets(Serbia_data, sheet='Food Expenditures (2007)')
p = read_sheets(Serbia_data, sheet='Food Prices (2007)')
d = read_sheets(Serbia_data, sheet='Household Characteristics')

In [40]:
x.head()
p.head()
d.head()

,i,t,m,index,women,girls,boys,men,Males 00-03,Females 00-03,...,Females 09-13,Males 14-18,Females 14-18,Males 19-30,Females 19-30,Males 31-50,Females 31-50,Males 51-99,Females 51-99,log HSize
0,7001700171001,2007,Sumadija,0,3,0,1,1,0,0,...,0,1,0,0,1,1,1,0,1,1.609438
1,7001700171002,2007,Sumadija,1,1,0,0,2,0,0,...,0,0,0,1,0,0,1,1,0,1.098612
2,7001700171004,2007,Sumadija,2,1,1,1,1,0,0,...,0,0,0,0,0,1,1,0,0,1.386294
3,7001700171005,2007,Sumadija,3,1,1,0,2,0,0,...,0,1,1,0,0,1,1,0,0,1.386294
4,7001700171007,2007,Sumadija,4,1,1,0,2,0,0,...,1,1,0,0,0,1,1,0,0,1.386294